name: Docker Image Build
on:
  push:
    tags:
      - "*"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/thomersch/varnish-vmod-reqwest:${{ env.VMOD_REQWEST_VERSION }}
          build-args: |
            VMOD_REQWEST_VERSION=${{ env.VMOD_REQWEST_VERSION }}
            RUST_VERSION=${{ env.RUST_VERSION }}
            VARNISH_VERSION_NODOT=${{ env.VARNISH_VERSION_NODOT }}
            VARNISH_VERSION=${{ env.VARNISH_VERSION }}
          platforms: linux/amd64,linux/arm64
        env:
          VMOD_REQWEST_VERSION: ${{ github.ref_name }}
          RUST_VERSION: 1.73-bookworm
          VARNISH_VERSION_NODOT: "75"
          VARNISH_VERSION: "7.5"
