name: Docker Image Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: thomersch/vmod_reqwest:0.0.3
